// Level 3 - The Wall. A river, a coast, and three walled cities.
// Teaches: catapults against walls, ports and the carrier system, siege patience.
export default {
  id: 3,
  name: 'The Wall',
  enemyTribe: 'bardur',
  difficulty: 3,
  turnLimit: 30,
  brief: 'Bardur holds the east bank behind walls (x4 defence). There is one land bridge. '
       + 'Catapults out-range defenders; ports let your units cross the water.',
  rows: [
    '.......~........',
    '..f....~~.f.....',
    '...m...~~..m....',
    '....f..~.....f..',
    '................',
    '.f.....~~....m..',
    '.....f.~...f....',
    '..m....~~.m...f.',
    '.......~~...m...',
    '...f...~..f.....',
    '.......~~...f...',
    '....m..~~...~~~~',
    '.f.....~.m..~~~~',
    '.....f.~~...~~~~',
    '.......~~...~~~#',
    '.......~....~~##',
  ],
  resources: [
    {"x": 2, "y": 13, "res": "fruit"},
    {"x": 1, "y": 13, "res": "fruit"},
    {"x": 3, "y": 12, "res": "crop"},
    {"x": 2, "y": 11, "res": "crop"},
    {"x": 3, "y": 9, "res": "game"},
    {"x": 2, "y": 7, "res": "metal"},
    {"x": 5, "y": 6, "res": "game"},
    {"x": 4, "y": 3, "res": "game"},
    {"x": 1, "y": 5, "res": "game"},
    {"x": 5, "y": 9, "res": "fruit"},
    {"x": 6, "y": 2, "res": "fruit"},
    {"x": 7, "y": 7, "res": "fish"},
    {"x": 7, "y": 10, "res": "fish"},
    {"x": 8, "y": 6, "res": "fish"},
    {"x": 13, "y": 12, "res": "fish"},
    {"x": 14, "y": 13, "res": "fish"},
    {"x": 10, "y": 1, "res": "game"},
    {"x": 13, "y": 3, "res": "game"},
    {"x": 11, "y": 6, "res": "fruit"},
    {"x": 10, "y": 9, "res": "fruit"},
    {"x": 13, "y": 5, "res": "metal"},
    {"x": 12, "y": 8, "res": "metal"},
  ],
  cities: [
    {"x": 2, "y": 12, "owner": "player", "capital": true, "level": 3},
    {"x": 6, "y": 9, "owner": "player", "level": 2},
    {"x": 11, "y": 3, "owner": "enemy", "capital": true, "level": 3, "walls": true},
    {"x": 10, "y": 8, "owner": "enemy", "level": 2, "walls": true},
    {"x": 11, "y": 12, "owner": "enemy", "level": 2},
    {"x": 5, "y": 2, "owner": null, "level": 1},
    {"x": 2, "y": 9, "owner": null, "level": 1},
    {"x": 10, "y": 12, "owner": null, "level": 1},
  ],
  units: [
    {"x": 2, "y": 12, "owner": "player", "type": "warrior"},
    {"x": 6, "y": 9, "owner": "player", "type": "warrior"},
    {"x": 3, "y": 10, "owner": "player", "type": "warrior"},
    {"x": 11, "y": 3, "owner": "enemy", "type": "defender"},
    {"x": 10, "y": 8, "owner": "enemy", "type": "defender"},
    {"x": 11, "y": 12, "owner": "enemy", "type": "warrior"},
  ],
  objective: { kind: 'capture_count', target: 4 },
};
