// Level 4 - Ragnarok. Full ruleset, strongest AI, superunits in play.
// Objective is score at the turn limit, so a stalled war still has to be won on points.
export default {
  id: 4,
  name: 'Ragnarok',
  enemyTribe: 'xinxi',
  difficulty: 4,
  turnLimit: 30,
  brief: 'Xin-xi hold the mountains with a full economy. Thirty turns. Highest score wins - '
       + 'a Giant from a level 5 city may decide it.',
  rows: [
    '..................',
    '..f.........f.....',
    '.....f...f...m....',
    '...m...m.......f..',
    '.f.........f......',
    '....f.........m...',
    '................f.',
    '......m.#..m......',
    '..f....~~~...f....',
    '......~~~~~.....m.',
    '.m...f.~~~........',
    '........~...m..f..',
    '....m.............',
    '...f........f.....',
    '.......m......m...',
    '......f...m.....f.',
    '.f.......f........',
    '..................',
  ],
  resources: [
    {"x": 2, "y": 15, "res": "fruit"},
    {"x": 1, "y": 14, "res": "fruit"},
    {"x": 3, "y": 15, "res": "crop"},
    {"x": 2, "y": 13, "res": "crop"},
    {"x": 3, "y": 13, "res": "game"},
    {"x": 4, "y": 12, "res": "metal"},
    {"x": 5, "y": 10, "res": "game"},
    {"x": 2, "y": 8, "res": "fruit"},
    {"x": 1, "y": 10, "res": "metal"},
    {"x": 15, "y": 2, "res": "fruit"},
    {"x": 16, "y": 3, "res": "fruit"},
    {"x": 14, "y": 2, "res": "crop"},
    {"x": 15, "y": 4, "res": "crop"},
    {"x": 15, "y": 3, "res": "game"},
    {"x": 13, "y": 2, "res": "metal"},
    {"x": 11, "y": 4, "res": "game"},
    {"x": 16, "y": 6, "res": "fruit"},
    {"x": 14, "y": 5, "res": "metal"},
    {"x": 8, "y": 9, "res": "fish"},
    {"x": 7, "y": 10, "res": "fish"},
    {"x": 9, "y": 10, "res": "fish"},
    {"x": 8, "y": 7, "res": "whale"},
    {"x": 5, "y": 5, "res": "fruit"},
    {"x": 12, "y": 13, "res": "fruit"},
    {"x": 6, "y": 15, "res": "game"},
  ],
  cities: [
    {"x": 2, "y": 14, "owner": "player", "capital": true, "level": 3},
    {"x": 4, "y": 10, "owner": "player", "level": 2},
    {"x": 15, "y": 3, "owner": "enemy", "capital": true, "level": 3, "walls": true},
    {"x": 13, "y": 7, "owner": "enemy", "level": 2, "walls": true},
    {"x": 12, "y": 14, "owner": null, "level": 1},
    {"x": 6, "y": 4, "owner": null, "level": 1},
    {"x": 9, "y": 13, "owner": null, "level": 1},
    {"x": 16, "y": 12, "owner": null, "level": 1},
    {"x": 4, "y": 2, "owner": null, "level": 1},
  ],
  units: [
    {"x": 2, "y": 14, "owner": "player", "type": "warrior"},
    {"x": 4, "y": 10, "owner": "player", "type": "warrior"},
    {"x": 15, "y": 3, "owner": "enemy", "type": "warrior"},
    {"x": 13, "y": 7, "owner": "enemy", "type": "defender"},
    {"x": 11, "y": 6, "owner": "enemy", "type": "rider"},
    {"x": 14, "y": 9, "owner": "enemy", "type": "archer"},
  ],
  objective: { kind: 'outscore' },
};
