// Level 2 - Expansion. Neutral villages, real economy decisions.
// Teaches: stars per turn, tech cost scaling with city count, city level-up rewards.
export default {
  id: 2,
  name: 'Expansion',
  enemyTribe: 'imperius',
  difficulty: 2,
  turnLimit: 25,
  brief: 'Four unclaimed villages sit between you and Imperius. Every city you take '
       + 'raises the price of every future technology - expand, but choose your techs.',
  rows: [
    '......m.......',
    '....f....f....',
    '......f....m..',
    '..............',
    '..f...f....f..',
    '...m.....m....',
    '.f.....f....f.',
    '.....m........',
    '...f....f...m.',
    '.......f......',
    '..m...........',
    '.....f....f...',
    '........m.....',
    '..............',
  ],
  resources: [
    {"x": 2, "y": 11, "res": "fruit"},
    {"x": 3, "y": 11, "res": "fruit"},
    {"x": 3, "y": 8, "res": "game"},
    {"x": 1, "y": 10, "res": "crop"},
    {"x": 4, "y": 10, "res": "crop"},
    {"x": 11, "y": 2, "res": "fruit"},
    {"x": 10, "y": 2, "res": "fruit"},
    {"x": 9, "y": 1, "res": "game"},
    {"x": 12, "y": 3, "res": "crop"},
    {"x": 9, "y": 3, "res": "crop"},
    {"x": 5, "y": 5, "res": "fruit"},
    {"x": 8, "y": 8, "res": "fruit"},
    {"x": 6, "y": 4, "res": "game"},
    {"x": 7, "y": 6, "res": "game"},
    {"x": 3, "y": 5, "res": "metal"},
    {"x": 9, "y": 5, "res": "metal"},
  ],
  cities: [
    {"x": 2, "y": 11, "owner": "player", "capital": true, "level": 1},
    {"x": 11, "y": 2, "owner": "enemy", "capital": true, "level": 1},
    {"x": 4, "y": 5, "owner": null, "level": 1},
    {"x": 9, "y": 8, "owner": null, "level": 1},
    {"x": 11, "y": 10, "owner": null, "level": 1},
    {"x": 2, "y": 3, "owner": null, "level": 1},
  ],
  units: [
    {"x": 2, "y": 11, "owner": "player", "type": "warrior"},
    {"x": 11, "y": 2, "owner": "enemy", "type": "warrior"},
  ],
  objective: { kind: 'score', target: 1150 },
};
